Sink implementation for Google Cloud Storage
siddhi-io/siddhi-io-gcs pull request #2
Opened 2019-09-20 12:01 UTC by CharukaK

## Purpose
This PR contains the Sink implementation for Google Cloud Storage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
JDK v1.8.0_211

2019-09-20 12:22 UTC, niveathika requested changes

2019-09-20 12:22 UTC, niveathika commented on README.md
> +**Using the extension as a [java library](https://siddhi-io.github.io/siddhi/documentation/siddhi-5.x/user-guide-5.x/#using-siddhi-as-a-java-library)**
Use latest README format in extensions

2019-09-20 12:22 UTC, niveathika commented on component/pom.xml
> +                            io.siddhi.extension.io.gcs.*
export-package is given twicw

2019-09-20 12:22 UTC, niveathika commented on component/pom.xml
> +                            io.siddhi.core.*;version="${siddhi.version.range}",
Import siddhi core once

2019-09-20 12:22 UTC, niveathika commented on component/src/main/java/io/siddhi/extension/io/gcs/sink/GCSSink.java
> +        parameters = {
Description

2019-09-20 12:22 UTC, niveathika commented on component/src/main/java/io/siddhi/extension/io/gcs/sink/GCSSink.java
> +    @Override
Remove default comments

2019-09-20 12:22 UTC, niveathika commented on component/src/main/java/io/siddhi/extension/io/gcs/sink/internal/beans/GCSSinkConfig.java
> +                    this.enableVersioning = Boolean.parseBoolean(
default values?

2019-09-20 12:22 UTC, niveathika commented on component/src/test/resources/testng.xml
> +<!--            <class name="io.siddhi.extension.io.gcs.sink.TestCaseOfGCSSink"/>-->
Add a comment about disabling tests

2019-09-20 12:22 UTC, niveathika commented on docs/images/siddhi-logo-w.svg
> +<!--
Use latest artefacts for docs, add a license for docs/license

2019-09-20 12:22 UTC, niveathika commented on mkdocs.yml
> +site_description: Siddhi IO GCS Extension
Complete as same as the latest extensions

2019-09-20 12:22 UTC, niveathika commented on pom.xml
> +                <version>6.11</version>
Move versions to properties

2019-09-20 12:22 UTC, niveathika commented on component/src/test/java/io/siddhi/extension/io/gcs/sink/TestCaseOfGCSSink.java
> +package io.siddhi.extension.io.gcs.sink;
License

2019-09-20 12:22 UTC, niveathika commented on component/src/main/java/io/siddhi/extension/io/gcs/util/ServiceClient.java
> +
remove unnecessary lines

2019-09-20 13:21 UTC, niveathika approved these changes

2019-09-20 13:21 UTC, merged

2020-05-11 11:10 UTC, niruhan commented on .gitignore
> +# CMake
shall we remove these placeholders?

2020-05-11 11:10 UTC, niruhan commented on checkstyle-suppressions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
can we safely remove this file?

2020-05-11 11:10 UTC, niruhan commented on component/pom.xml
> +
shall we remove the newline

2020-05-11 11:10 UTC, niruhan commented on component/src/main/java/io/siddhi/extension/io/gcs/sink/GCSSink.java
> +                @Example(
shall we add one example with optional parameters?

2020-05-11 11:10 UTC, niruhan commented on component/src/main/java/io/siddhi/extension/io/gcs/sink/GCSSink.java
> +    @Override
can we remove this overriding?

2020-05-11 15:19 UTC, dilini-muthumala commented on component/src/main/java/io/siddhi/extension/io/gcs/util/ServiceClient.java
> +
It's better to remove unnecessary empty lines.

2020-05-11 15:19 UTC, dilini-muthumala commented on component/src/main/java/io/siddhi/extension/io/gcs/util/ServiceClient.java
> +
It's better to remove unnecessary empty lines.